# Generated by Django 4.0.5 on 2022-08-03 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_books_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0003_rename_carts_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('order placed', 'order placed'), ('order cancelled', 'order cancelled'), ('dispatched', 'dispatched'), ('in-transit', 'in-transit'), ('delivered', 'delivered')], default='order placed', max_length=120)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
