# Generated by Django 4.0.5 on 2022-07-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=120)),
                ('desig', models.CharField(max_length=100)),
                ('exp', models.PositiveIntegerField()),
                ('salary', models.PositiveIntegerField()),
            ],
        ),
    ]
